### ISSUE TITLE
Is ngx_http_dav_module required?

### ISSUE THREAD

**Issue by bilke** [Daniel15/simple-nuget-server#11]
There is a `dav_methods`-directive in the nginx-config. Is the module `ngx_http_dav_module` required? If yes please add this to the Readme.

I dont have this module installed. I commented out the directive and now my pushes seem to do nothing (nuget says it was uploaded but the `packagefiles`-dir stays empty).

**Comment by Daniel15** [comment]
Yes, it's required in order to allow the `PUT` method.

**Comment by Daniel15** [comment]
Added note to the readme: https://github.com/Daniel15/simple-nuget-server/commit/8fb297515126cf5a2ebf47c4c6800c99d30bc0a7
